source("SCRIPT - Instalação de Pacotes.R", local = FALSE)
source("SCRIPT - Funções.R", local = FALSE, echo=FALSE)
source("SCRIPT - Leitura de Planilhas.R", local = FALSE, echo=FALSE)
source("SCRIPT - Preparação Dados.R", local = FALSE, echo=TRUE)
source("SCRIPT - Estatísticas.R", local = FALSE, echo=TRUE)
source("SCRIPT - Top 10  Concedentes.R", local = FALSE, echo=TRUE)
source("SCRIPT - Top 31  Convenentes.R", local = FALSE, echo=TRUE)
# source("SCRIPT - Graficos Concedentes.R", local = FALSE, echo=TRUE) 
# source("SCRIPT - Graficos Convenentes.R", local = FALSE, echo=TRUE) 